import { Router } from "express";
import { randomUUID } from "node:crypto";
import { getDb } from "../db/connection.js";

const router = Router();

router.get("/", (req, res) => {
  const db = getDb();
  const districtId = req.query.district as string | undefined;
  const rows = districtId
    ? db.prepare(`SELECT * FROM reports WHERE district_id = ? ORDER BY generated_at DESC`).all(districtId)
    : db.prepare(`SELECT * FROM reports ORDER BY generated_at DESC`).all();
  res.json({ reports: rows });
});

router.get("/:id", (req, res) => {
  const db = getDb();
  const row = db.prepare(`SELECT * FROM reports WHERE id = ?`).get(req.params.id);
  if (!row) return res.status(404).json({ error: "Report not found" });
  res.json({ report: row });
});

router.delete("/:id", (req, res) => {
  const db = getDb();
  const result = db.prepare(`DELETE FROM reports WHERE id = ?`).run(req.params.id);
  if (result.changes === 0) return res.status(404).json({ error: "Report not found" });
  res.json({ ok: true });
});

// Endpoint that "generates" a fresh executive summary by aggregating from the DB.
// In a real system this would call ETL + a templated PDF generator. For demo
// purposes it just returns the aggregated structure the frontend can render.
router.post("/generate", (req, res) => {
  const db = getDb();
  const districtId = req.body?.district || "ash-shati-ash-sharqi";
  const district = db.prepare(`SELECT * FROM districts WHERE id = ?`).get(districtId) as any;
  if (!district) return res.status(404).json({ error: "District not found" });

  const kpis = db.prepare(`SELECT * FROM district_kpis WHERE district_id = ?`).all(districtId);
  const insights = db
    .prepare(`SELECT * FROM insights WHERE district_id = ? ORDER BY position`)
    .all(districtId) as any[];

  const counts = {
    critical: insights.filter((i) => i.severity === "CRITICAL").length,
    high: insights.filter((i) => i.severity === "HIGH").length,
    medium: insights.filter((i) => i.severity === "MEDIUM").length,
    positive: insights.filter((i) => i.severity === "POSITIVE").length,
    opportunity: insights.filter((i) => i.severity === "OPPORTUNITY").length,
  };

  res.json({
    generated_at: new Date().toISOString(),
    district,
    kpis,
    insights,
    summary: { ...counts, total: insights.length },
  });
});

// Generate a new report entry the user can download. The PoC version always
// produces the same MOMAH PDF; future iterations would compose it dynamically.
router.post("/generate-pdf", (req, res) => {
  const db = getDb();
  const districtId = req.body?.district || "ash-shati-ash-sharqi";
  const area = req.body?.area || "All areas";
  const layer = req.body?.layer || "All layers";
  const district = db.prepare(`SELECT name, name_ar FROM districts WHERE id = ?`).get(districtId) as
    | { name: string; name_ar: string }
    | undefined;
  const districtName = district?.name ?? "Ash Shati Ash Sharqi";
  const districtNameAr = district?.name_ar ?? "الشاطئ الشرقي";

  const id = `rpt-gen-${randomUUID().slice(0, 8)}`;
  const now = new Date().toISOString();
  const dateStr = now.slice(0, 10);

  db.prepare(`
    INSERT INTO reports (id, district_id, title_en, title_ar, kind, description_en, description_ar,
                         file_path, generated_at, author)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `).run(
    id,
    districtId,
    `MOMAH Ash Shati Insights — ${dateStr}`,
    `رؤى الشاطئ الشرقي لوزارة البلديات — ${dateStr}`,
    "generated",
    `On-demand insights report generated by Rashid · scope: ${area} · layers: ${layer}.`,
    `تقرير رؤى عند الطلب أنشأه راشد · النطاق: ${area} · الطبقات: ${layer}.`,
    "/reports/MOMAH_Ash_Shati_Insights_EN.pdf",
    now,
    "Rashid Digital GIS Employee",
  );

  const report = db.prepare(`SELECT * FROM reports WHERE id = ?`).get(id);
  res.json({ report });
});

export default router;
