import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import html2canvas from "html2canvas";
import { cityStats } from "../data/mockData";

const BRAND_GREEN = "#26634B";
const BRAND_DARK = "#160F3E";

async function captureElement(selector: string): Promise<string | null> {
  const el = document.querySelector(selector) as HTMLElement | null;
  if (!el) return null;
  const canvas = await html2canvas(el, {
    backgroundColor: "#ffffff",
    scale: 2,
    useCORS: true,
    logging: false,
  });
  return canvas.toDataURL("image/png");
}

export async function exportAnalysisReport(opts: {
  request: string;
  lang: "en" | "ar";
  mapSelector?: string;
  chartSelector?: string;
}) {
  const { request, lang, mapSelector = "#map-container", chartSelector = "#growth-chart" } = opts;
  const t = (en: string, ar: string) => (lang === "en" ? en : ar);

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 40;
  const now = new Date();

  // --- Header banner ---
  doc.setFillColor(BRAND_GREEN);
  doc.rect(0, 0, pageW, 80, "F");
  doc.setTextColor("#ffffff");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(t("Urban Expansion Analysis Report", "تقرير تحليل التوسع العمراني"), margin, 35);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(t("Generated by Rashid • Geospatial AI Agent", "أُنشئ بواسطة راشد • وكيل الذكاء الجيومكاني"), margin, 55);
  doc.text(now.toISOString().slice(0, 10), pageW - margin, 55, { align: "right" });

  let y = 110;

  // --- Request block ---
  doc.setTextColor(BRAND_DARK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(t("ANALYSIS REQUEST", "طلب التحليل"), margin, y);
  y += 14;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor("#323232");
  const wrapped = doc.splitTextToSize(request || t("(none)", "(لا يوجد)"), pageW - margin * 2);
  doc.text(wrapped, margin, y);
  y += wrapped.length * 14 + 10;

  // --- Summary stats cards ---
  const totalExpansion = cityStats.reduce((s, c) => s + c.expansion, 0);
  const totalPrev = cityStats.reduce((s, c) => s + c.area2024, 0);
  const avgGrowth = ((totalExpansion / totalPrev) * 100).toFixed(2);
  const topGrowth = cityStats.reduce((a, b) => (a.growthPct > b.growthPct ? a : b));

  const cards: { label: string; value: string; unit: string }[] = [
    { label: t("Total Expansion", "إجمالي التوسع"), value: `${totalExpansion}`, unit: "km²" },
    { label: t("Avg Growth", "متوسط النمو"), value: `${avgGrowth}%`, unit: t("YoY", "سنوياً") },
    { label: t("Cities", "المدن"), value: `${cityStats.length}`, unit: t("analyzed", "محللة") },
    { label: t("Top Grower", "الأعلى نمواً"), value: lang === "en" ? topGrowth.name : topGrowth.nameAr, unit: `${topGrowth.growthPct}%` },
  ];
  const cardW = (pageW - margin * 2 - 3 * 10) / 4;
  cards.forEach((c, i) => {
    const x = margin + i * (cardW + 10);
    doc.setFillColor(BRAND_DARK);
    doc.roundedRect(x, y, cardW, 58, 6, 6, "F");
    doc.setTextColor("#ffffff");
    doc.setFontSize(8);
    doc.text(c.label, x + 10, y + 16);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(c.value, x + 10, y + 38);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(c.unit, x + 10, y + 50);
  });
  y += 74;

  // --- Map snapshot (before/after, heatmap) ---
  const mapImg = await captureElement(mapSelector);
  if (mapImg) {
    doc.setTextColor(BRAND_DARK);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text(t("BEFORE vs AFTER — BOUNDARY OVERLAY", "قبل وبعد — تراكب الحدود"), margin, y);
    y += 8;
    const imgW = pageW - margin * 2;
    const imgH = imgW * 0.55;
    doc.addImage(mapImg, "PNG", margin, y + 4, imgW, imgH);
    y += imgH + 18;
  }

  // --- Stats table ---
  if (y > 680) {
    doc.addPage();
    y = margin;
  }
  doc.setTextColor(BRAND_DARK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(t("CITY-LEVEL BREAKDOWN", "التفصيل على مستوى المدن"), margin, y);
  y += 6;

  autoTable(doc, {
    startY: y + 4,
    head: [[
      t("City", "المدينة"),
      "2024 (km²)",
      "2025 (km²)",
      t("Expansion", "التوسع"),
      t("Growth %", "النمو %"),
    ]],
    body: cityStats.map((c) => [
      lang === "en" ? c.name : c.nameAr,
      c.area2024.toLocaleString(),
      c.area2025.toLocaleString(),
      `+${c.expansion}`,
      `${c.growthPct}%`,
    ]),
    theme: "grid",
    headStyles: { fillColor: BRAND_GREEN, textColor: "#ffffff", fontStyle: "bold" },
    alternateRowStyles: { fillColor: "#FAFAFA" },
    margin: { left: margin, right: margin },
    styles: { fontSize: 10, cellPadding: 6 },
  });
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 18;

  // --- Chart snapshot ---
  const chartImg = await captureElement(chartSelector);
  if (chartImg) {
    if (y > 600) {
      doc.addPage();
      y = margin;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(BRAND_DARK);
    doc.text(t("GROWTH CHART", "رسم النمو"), margin, y);
    y += 8;
    const imgW = pageW - margin * 2;
    const imgH = imgW * 0.45;
    doc.addImage(chartImg, "PNG", margin, y + 4, imgW, imgH);
    y += imgH + 18;
  }

  // --- Methodology + sources ---
  if (y > 680) {
    doc.addPage();
    y = margin;
  }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(BRAND_DARK);
  doc.text(t("METHODOLOGY & SOURCES", "المنهجية والمصادر"), margin, y);
  y += 14;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor("#323232");
  const method = [
    t(
      "• Data: 12 SDI layers — urban boundaries, subdivision plans, land-use (2024 & 2025).",
      "• البيانات: 12 طبقة من البنية المكانية — حدود عمرانية ومخططات تقسيم واستخدام أراضي (2024 و 2025)."
    ),
    t(
      "• Quality: CRS EPSG:4326 aligned, 10/10 shapefiles validated, no gaps.",
      "• الجودة: محاذاة CRS EPSG:4326، تحقق 10/10 من الملفات، بدون فجوات."
    ),
    t(
      "• Analysis: symmetric-difference overlay between 2024 and 2025 boundaries.",
      "• التحليل: تراكب الفرق المتماثل بين حدود 2024 و 2025."
    ),
    t(
      "• Provenance: methodology v2.1, timestamp 2026-04-15T12:00Z.",
      "• المصادر: المنهجية v2.1، الطابع الزمني 2026-04-15T12:00Z."
    ),
    t(
      "• Flags: Dammam growth (4.07%) above Q2 trend — reviewer-confirmed.",
      "• التنبيهات: نمو الدمام (4.07%) يتجاوز اتجاه الربع الثاني — تم تأكيد المراجعة."
    ),
  ];
  method.forEach((line) => {
    const w = doc.splitTextToSize(line, pageW - margin * 2);
    doc.text(w, margin, y);
    y += w.length * 12 + 4;
  });

  // --- Footer on each page ---
  const total = (doc as unknown as { getNumberOfPages: () => number }).getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    doc.setFontSize(8);
    doc.setTextColor("#888888");
    doc.text(
      t(
        "Rashid • Geospatial AI Agent — Ministry of Municipalities & Housing",
        "راشد • وكيل الذكاء الجيومكاني — وزارة البلديات والإسكان"
      ),
      margin,
      doc.internal.pageSize.getHeight() - 20
    );
    doc.text(`${p} / ${total}`, pageW - margin, doc.internal.pageSize.getHeight() - 20, {
      align: "right",
    });
  }

  doc.save(`rashid-urban-expansion-${now.toISOString().slice(0, 10)}.pdf`);
}
